(() => {
  'use strict';

  const languages = ['ja', 'en', 'zh-CN', 'zh-TW', 'ko', 'es', 'fr', 'de', 'pt'];
  const rows = [
    ['META ZERO | eye-factory','META ZERO | eye-factory','META ZERO | eye-factory','META ZERO | eye-factory','META ZERO | eye-factory','META ZERO | eye-factory','META ZERO | eye-factory','META ZERO | eye-factory','META ZERO | eye-factory'],
    ['変換画面へ移動','Go to converter','前往转换工具','前往轉換工具','변환 화면으로 이동','Ir al conversor','Accéder au convertisseur','Zum Konverter','Ir para o conversor'],
    ['変換','Convert','转换','轉換','변환','Convertir','Convertir','Konvertieren','Converter'],
    ['安全性','Privacy','隐私','隱私','안전성','Privacidad','Confidentialité','Datenschutz','Privacidade'],
    ['使い方','Guide','使用方法','使用方法','사용법','Guía','Guide','Anleitung','Guia'],
    ['概要','Overview','概览','概覽','개요','Resumen','Aperçu','Übersicht','Visão geral'],
    ['写真と動画から、残したくないデジタル情報をゼロへ。','Remove unwanted digital traces from photos and videos.','清除照片和视频中不想保留的数字信息。','清除照片和影片中不想保留的數位資訊。','사진과 동영상에서 남기고 싶지 않은 디지털 정보를 제거합니다.','Elimina datos digitales no deseados de fotos y vídeos.','Supprimez les traces numériques indésirables de vos photos et vidéos.','Entfernen Sie unerwünschte digitale Spuren aus Fotos und Videos.','Remova informações digitais indesejadas de fotos e vídeos.'],
    ['GPS、撮影日時、端末名、編集ソフト情報などを、ファイルを外へ送らず端末内で除去します。','Remove GPS, capture dates, device names, editing software data and more locally, without sending files away.','无需上传文件，即可在设备内删除GPS、拍摄时间、设备名称、编辑软件等信息。','無需上傳檔案，即可在裝置內刪除GPS、拍攝時間、裝置名稱、編輯軟體等資訊。','파일을 외부로 보내지 않고 GPS, 촬영 시각, 기기명, 편집 소프트웨어 정보 등을 기기 안에서 제거합니다.','Elimina GPS, fechas, nombres de dispositivo y datos del editor de forma local, sin enviar archivos.','Supprime le GPS, les dates, le nom de l’appareil et les données du logiciel localement, sans envoyer les fichiers.','Entfernt GPS, Aufnahmedaten, Gerätenamen und Softwaredaten lokal, ohne Dateien zu versenden.','Remove GPS, datas, nomes de dispositivo e dados do editor localmente, sem enviar arquivos.'],
    ['今すぐ変換する','Convert now','立即转换','立即轉換','지금 변환','Convertir ahora','Convertir maintenant','Jetzt konvertieren','Converter agora'],
    ['仕組みを見る','How it works','查看原理','查看原理','작동 방식','Cómo funciona','Comment ça marche','So funktioniert es','Como funciona'],
    ['アップロードなし','No uploads','无需上传','無需上傳','업로드 없음','Sin subidas','Aucun envoi','Keine Uploads','Sem uploads'],
    ['1件ずつ省メモリ処理','Memory-efficient one-by-one processing','逐个低内存处理','逐一節省記憶體處理','한 번에 하나씩 메모리 절약 처리','Procesamiento eficiente uno por uno','Traitement économe, un fichier à la fois','Speichersparend einzeln verarbeiten','Processamento econômico, um por vez'],
    ['スマートフォン対応','Mobile friendly','支持手机','支援手機','스마트폰 지원','Compatible con móvil','Compatible mobile','Mobil geeignet','Compatível com celular'],
    ['端末の中だけで変換','Convert entirely on your device','仅在设备内转换','僅在裝置內轉換','기기 안에서만 변환','Conversión solo en tu dispositivo','Conversion uniquement sur votre appareil','Konvertierung nur auf Ihrem Gerät','Conversão somente no dispositivo'],
    ['画像は最大10件、動画は最大3件。選択した順に1件ずつ処理します。','Up to 10 images or 3 videos, processed one at a time in selection order.','最多10张图片或3个视频，按选择顺序逐个处理。','最多10張圖片或3部影片，依選取順序逐一處理。','이미지 최대 10개, 동영상 최대 3개를 선택 순서대로 하나씩 처리합니다.','Hasta 10 imágenes o 3 vídeos, procesados uno a uno.','Jusqu’à 10 images ou 3 vidéos, traitées une par une.','Bis zu 10 Bilder oder 3 Videos, einzeln verarbeitet.','Até 10 imagens ou 3 vídeos, processados um por vez.'],
    ['ファイルは送信されません','Your files are never uploaded','文件不会上传','檔案不會上傳','파일은 전송되지 않습니다','Tus archivos no se suben','Vos fichiers ne sont jamais envoyés','Ihre Dateien werden nicht hochgeladen','Seus arquivos não são enviados'],
    ['選択・変換・保存のすべてが、この端末のブラウザ内で完結します。','Selection, conversion and saving all happen inside this browser.','选择、转换和保存均在本设备的浏览器内完成。','選取、轉換與儲存都在本裝置的瀏覽器內完成。','선택, 변환, 저장이 모두 이 기기의 브라우저 안에서 끝납니다.','La selección, conversión y descarga se realizan en este navegador.','La sélection, la conversion et l’enregistrement se font dans ce navigateur.','Auswahl, Konvertierung und Speichern erfolgen vollständig in diesem Browser.','Seleção, conversão e salvamento ocorrem neste navegador.'],
    ['画像','Images','图片','圖片','이미지','Imágenes','Images','Bilder','Imagens'],
    ['最大10件','Up to 10','最多10个','最多10個','최대 10개','Hasta 10','Jusqu’à 10','Bis zu 10','Até 10'],
    ['動画','Videos','视频','影片','동영상','Vídeos','Vidéos','Videos','Vídeos'],
    ['最大3件','Up to 3','最多3个','最多3個','최대 3개','Hasta 3','Jusqu’à 3','Bis zu 3','Até 3'],
    ['画像をここにドロップ','Drop images here','将图片拖到这里','將圖片拖到這裡','이미지를 여기에 놓으세요','Suelta imágenes aquí','Déposez les images ici','Bilder hier ablegen','Solte as imagens aqui'],
    ['動画をここにドロップ','Drop videos here','将视频拖到这里','將影片拖到這裡','동영상을 여기에 놓으세요','Suelta vídeos aquí','Déposez les vidéos ici','Videos hier ablegen','Solte os vídeos aqui'],
    ['またはタップして選択','or tap to choose','或点击选择','或點按選取','또는 눌러서 선택','o toca para elegir','ou touchez pour choisir','oder antippen zum Auswählen','ou toque para escolher'],
    ['JPEG / PNG / WebP（静止画）・ 1枚あたり最大64MP','JPEG / PNG / static WebP · up to 64 MP each','JPEG / PNG / 静态WebP · 每张最大64MP','JPEG / PNG / 靜態WebP · 每張最大64MP','JPEG / PNG / 정지 WebP · 장당 최대 64MP','JPEG / PNG / WebP estático · hasta 64 MP','JPEG / PNG / WebP statique · jusqu’à 64 MP','JPEG / PNG / statisches WebP · bis 64 MP','JPEG / PNG / WebP estático · até 64 MP'],
    ['最大3件 ・ 1件最大1GB ・ 4K相当まで','Up to 3 · 1 GB each · up to 4K','最多3个 · 每个最大1GB · 最高4K','最多3個 · 每個最大1GB · 最高4K','최대 3개 · 개당 1GB · 최대 4K','Hasta 3 · 1 GB cada uno · hasta 4K','Jusqu’à 3 · 1 Go chacun · jusqu’à 4K','Bis zu 3 · je 1 GB · bis 4K','Até 3 · 1 GB cada · até 4K'],
    ['端末由来の特徴を弱める','Reduce device-derived patterns','弱化设备来源特征','弱化裝置來源特徵','기기 유래 특징 약화','Reducir patrones del dispositivo','Réduire les signatures de l’appareil','Gerätemuster abschwächen','Reduzir padrões do dispositivo'],
    ['見た目に影響しない微細な再生成処理を加えます','Adds a subtle regeneration pass designed to preserve appearance','添加尽量不影响外观的细微重建处理','加入盡量不影響外觀的細微重建處理','외관에 영향을 주지 않는 미세 재생성 처리를 더합니다','Añade una regeneración sutil sin afectar la apariencia','Ajoute une régénération subtile sans altérer l’apparence','Fügt eine unauffällige Neugenerierung hinzu','Adiciona regeneração sutil sem afetar a aparência'],
    ['JPEG / WebP 品質','JPEG / WebP quality','JPEG / WebP质量','JPEG / WebP品質','JPEG / WebP 품질','Calidad JPEG / WebP','Qualité JPEG / WebP','JPEG-/WebP-Qualität','Qualidade JPEG / WebP'],
    ['最高','Maximum','最高','最高','최고','Máxima','Maximale','Maximal','Máxima'],
    ['高品質','High quality','高质量','高品質','고품질','Alta','Élevée','Hoch','Alta'],
    ['標準','Standard','标准','標準','표준','Estándar','Standard','Standard','Padrão'],
    ['すべて外す','Remove all','全部移除','全部移除','모두 제거','Quitar todo','Tout retirer','Alle entfernen','Remover tudo'],
    ['画像を変換','Convert images','转换图片','轉換圖片','이미지 변환','Convertir imágenes','Convertir les images','Bilder konvertieren','Converter imagens'],
    ['動画を変換','Convert videos','转换视频','轉換影片','동영상 변환','Convertir vídeos','Convertir les vidéos','Videos konvertieren','Converter vídeos'],
    ['動画は再生時間とほぼ同じ処理時間がかかります。','Video processing takes approximately the video’s playback time.','视频处理时间与播放时长大致相同。','影片處理時間與播放時長大致相同。','동영상 처리에는 재생 시간과 거의 같은 시간이 걸립니다.','El proceso tarda aproximadamente lo mismo que el vídeo.','Le traitement dure environ le temps de lecture de la vidéo.','Die Verarbeitung dauert ungefähr so lange wie das Video.','O processamento leva aproximadamente a duração do vídeo.'],
    ['300MBを超えるファイルは、対応PCブラウザで保存先へ直接書き込む「大容量モード」を利用します。','Files over 300 MB use direct-to-disk Large File Mode in supported desktop browsers.','超过300MB的文件将在支持的桌面浏览器中使用直接写入保存位置的大文件模式。','超過300MB的檔案會在支援的桌面瀏覽器中使用直接寫入儲存位置的大檔案模式。','300MB를 넘는 파일은 지원 PC 브라우저에서 저장 위치에 직접 쓰는 대용량 모드를 사용합니다.','Los archivos de más de 300 MB usan el modo grande con escritura directa en navegadores compatibles.','Les fichiers de plus de 300 Mo utilisent le mode grande taille avec écriture directe.','Dateien über 300 MB werden in unterstützten Desktop-Browsern direkt gespeichert.','Arquivos acima de 300 MB usam modo grande com gravação direta.'],
    ['動画機能を確認しています…','Checking video support…','正在检查视频支持…','正在檢查影片支援…','동영상 기능 확인 중…','Comprobando compatibilidad…','Vérification de la prise en charge vidéo…','Videounterstützung wird geprüft…','Verificando suporte a vídeo…'],
    ['処理しています','Processing','处理中','處理中','처리 중','Procesando','Traitement','Verarbeitung','Processando'],
    ['準備中…','Preparing…','准备中…','準備中…','준비 중…','Preparando…','Préparation…','Vorbereitung…','Preparando…'],
    ['処理を中止','Cancel processing','取消处理','取消處理','처리 중지','Cancelar proceso','Annuler le traitement','Verarbeitung abbrechen','Cancelar processamento'],
    ['消す情報と、変えない中身','What is removed and what remains','删除的信息与保留的内容','刪除的資訊與保留的內容','제거하는 정보와 유지하는 내용','Qué se elimina y qué se conserva','Ce qui est supprimé et ce qui reste','Was entfernt wird und was bleibt','O que é removido e o que permanece'],
    ['埋め込み情報を除去','Remove embedded metadata','删除嵌入信息','刪除嵌入資訊','내장 정보 제거','Eliminar metadatos incrustados','Supprimer les métadonnées intégrées','Eingebettete Metadaten entfernen','Remover metadados incorporados'],
    ['GPS座標・高度・方向・速度・場所名・住所','GPS coordinates, altitude, direction, speed, place names and addresses','GPS坐标、海拔、方向、速度、地点名称和地址','GPS座標、海拔、方向、速度、地點名稱與地址','GPS 좌표, 고도, 방향, 속도, 장소명, 주소','Coordenadas GPS, altitud, dirección, velocidad, lugares y direcciones','Coordonnées GPS, altitude, direction, vitesse, lieux et adresses','GPS-Koordinaten, Höhe, Richtung, Geschwindigkeit, Ortsnamen und Adressen','Coordenadas GPS, altitude, direção, velocidade, locais e endereços'],
    ['撮影・作成・更新日時、タイムゾーン','Capture, creation and modification times, and time zone','拍摄、创建、修改时间及时区','拍攝、建立、修改時間與時區','촬영·생성·수정 시각과 시간대','Fechas de captura, creación, modificación y zona horaria','Dates de prise, création, modification et fuseau horaire','Aufnahme-, Erstellungs- und Änderungszeit sowie Zeitzone','Datas de captura, criação, modificação e fuso horário'],
    ['メーカー・端末・カメラ・レンズ・シリアル識別子','Manufacturer, device, camera, lens and serial identifiers','厂商、设备、相机、镜头及序列标识','廠商、裝置、相機、鏡頭與序號識別碼','제조사, 기기, 카메라, 렌즈, 시리얼 식별자','Fabricante, dispositivo, cámara, objetivo e identificadores de serie','Fabricant, appareil, caméra, objectif et identifiants de série','Hersteller, Gerät, Kamera, Objektiv und Serienkennungen','Fabricante, dispositivo, câmera, lente e identificadores seriais'],
    ['作者・所有者・著作権・連絡先・タイトル・コメント','Author, owner, copyright, contact, title and comments','作者、所有者、版权、联系方式、标题和评论','作者、所有者、版權、聯絡方式、標題與註解','작성자, 소유자, 저작권, 연락처, 제목, 설명','Autor, propietario, copyright, contacto, título y comentarios','Auteur, propriétaire, droits, contact, titre et commentaires','Autor, Besitzer, Urheberrecht, Kontakt, Titel und Kommentare','Autor, proprietário, direitos, contato, título e comentários'],
    ['編集ソフト・エンコーダー・編集履歴・文書ID','Editing software, encoder, edit history and document IDs','编辑软件、编码器、编辑历史和文档ID','編輯軟體、編碼器、編輯歷程與文件ID','편집 소프트웨어, 인코더, 편집 기록, 문서 ID','Software de edición, codificador, historial e ID de documento','Logiciel de montage, encodeur, historique et identifiants de document','Bearbeitungssoftware, Encoder, Verlauf und Dokument-IDs','Software de edição, codificador, histórico e IDs de documento'],
    ['ユーザー名・端末名・ホスト名・IP・プロバイダ名・URL・メール・ネットワークパス','User, device and host names, IP, provider names, URLs, email and network paths','用户名、设备名、主机名、IP、网络服务商名称、URL、邮箱和网络路径','使用者名稱、裝置名稱、主機名稱、IP、網路服務商名稱、URL、郵件與網路路徑','사용자명, 기기명, 호스트명, IP, 통신사명, URL, 이메일, 네트워크 경로','Usuario, dispositivo, host, IP, proveedor, URL, correo y rutas de red','Utilisateur, appareil, hôte, IP, fournisseur, URL, e-mail et chemins réseau','Benutzer-, Geräte- und Hostname, IP, Providername, URLs, E-Mail und Netzwerkpfade','Usuário, dispositivo, host, IP, provedor, URLs, e-mail e caminhos de rede'],
    ['EXIF・XMP・IPTC・ICC・テキストチャンク','EXIF, XMP, IPTC, ICC and text chunks','EXIF、XMP、IPTC、ICC及文本块','EXIF、XMP、IPTC、ICC與文字區塊','EXIF, XMP, IPTC, ICC, 텍스트 청크','EXIF, XMP, IPTC, ICC y bloques de texto','EXIF, XMP, IPTC, ICC et blocs de texte','EXIF, XMP, IPTC, ICC und Textblöcke','EXIF, XMP, IPTC, ICC e blocos de texto'],
    ['埋め込みサムネイル・プレビュー・動画のチャプター／時限メタデータ','Embedded thumbnails, previews, video chapters and timed metadata','嵌入缩略图、预览、视频章节及时序元数据','嵌入縮圖、預覽、影片章節與時序中繼資料','내장 썸네일, 미리보기, 동영상 챕터, 시간 연동 메타데이터','Miniaturas, vistas previas, capítulos y metadatos temporizados','Miniatures, aperçus, chapitres et métadonnées temporelles','Eingebettete Vorschaubilder, Kapitel und zeitgesteuerte Metadaten','Miniaturas, prévias, capítulos e metadados temporizados'],
    ['端末由来の特徴を弱める','Reduce device-derived patterns','弱化设备来源特征','弱化裝置來源特徵','기기 유래 특징 약화','Reducir patrones del dispositivo','Réduire les signatures de l’appareil','Gerätemuster abschwächen','Reduzir padrões do dispositivo'],
    ['画像は微細な再生成、動画は映像と音声の再エンコードを行い、元ファイル固有の圧縮・記録パターンを引き継ぎにくくします。','Images receive a subtle regeneration pass; video and audio are re-encoded to reduce inherited compression and recording patterns.','图片进行细微重建，视频和音频重新编码，以减少原文件的压缩与记录特征。','圖片進行細微重建，影片與音訊重新編碼，以減少原檔案的壓縮與記錄特徵。','이미지는 미세 재생성, 동영상은 영상과 음성을 재인코딩하여 원본의 압축·기록 패턴을 이어받기 어렵게 합니다.','Las imágenes se regeneran sutilmente y el vídeo y audio se recodifican para reducir patrones heredados.','Les images sont régénérées subtilement et la vidéo et l’audio réencodés pour réduire les signatures héritées.','Bilder werden dezent neu erzeugt, Video und Audio neu kodiert, um geerbte Muster zu reduzieren.','Imagens são regeneradas sutilmente; vídeo e áudio são recodificados para reduzir padrões herdados.'],
    ['見た目の内容はそのまま','Visible content stays unchanged','可见内容保持不变','可見內容保持不變','보이는 내용은 그대로','El contenido visible no cambia','Le contenu visible reste inchangé','Sichtbare Inhalte bleiben unverändert','O conteúdo visível permanece'],
    ['写っている人物、住所、車のナンバー、画面内の文字などは自動で消しません。公開前に目視でも確認してください。','People, addresses, license plates and on-screen text are not removed automatically. Check the result before publishing.','不会自动删除画面中的人物、地址、车牌和文字。发布前请目视确认。','不會自動刪除畫面中的人物、地址、車牌與文字。發布前請目視確認。','화면 속 인물, 주소, 차량 번호, 문자는 자동으로 지우지 않습니다. 공개 전에 직접 확인하세요.','No elimina automáticamente personas, direcciones, matrículas ni texto visible. Revisa antes de publicar.','Les personnes, adresses, plaques et textes visibles ne sont pas supprimés. Vérifiez avant publication.','Personen, Adressen, Kennzeichen und sichtbarer Text werden nicht entfernt. Vor Veröffentlichung prüfen.','Pessoas, endereços, placas e textos visíveis não são removidos. Verifique antes de publicar.'],
    ['大切なお知らせ','Important notice','重要提示','重要提醒','중요 안내','Aviso importante','Avis important','Wichtiger Hinweis','Aviso importante'],
    ['デジタル匿名化に絶対の保証はありません。画面内に写る顔・住所・ナンバー・反射・音声は消さず、投稿先に伝わる通信元IPやプロバイダ情報も変更できません。META ZEROはファイル内部の情報を減らす補助ツールです。','Digital anonymity cannot be guaranteed. Faces, addresses, plates, reflections and audio remain visible, and the service you upload to can still see your connection IP and provider. META ZERO reduces information stored inside the file.','数字匿名无法绝对保证。画面中的人脸、地址、车牌、反射和声音不会被删除，上传平台仍可看到连接IP和网络服务商。META ZERO仅减少文件内部信息。','數位匿名無法絕對保證。畫面中的臉孔、地址、車牌、反射與聲音不會刪除，上傳平台仍可看到連線IP與網路服務商。META ZERO僅減少檔案內部資訊。','디지털 익명성을 절대 보장할 수 없습니다. 화면의 얼굴·주소·번호판·반사·음성은 남고, 게시 서비스는 접속 IP와 통신사를 알 수 있습니다. META ZERO는 파일 내부 정보를 줄이는 보조 도구입니다.','El anonimato absoluto no está garantizado. Rostros, direcciones, matrículas, reflejos y audio permanecen, y el servicio de destino puede ver tu IP y proveedor. META ZERO reduce la información interna del archivo.','L’anonymat absolu n’est pas garanti. Visages, adresses, plaques, reflets et audio restent visibles, et le service cible peut voir votre IP et fournisseur. META ZERO réduit les données internes du fichier.','Vollständige Anonymität ist nicht garantiert. Gesichter, Adressen, Kennzeichen, Spiegelungen und Ton bleiben; der Zielservice sieht weiterhin IP und Provider. META ZERO reduziert Dateiinformationen.','Anonimato absoluto não é garantido. Rostos, endereços, placas, reflexos e áudio permanecem, e o serviço de destino pode ver IP e provedor. META ZERO reduz informações internas do arquivo.'],
    ['元ファイルは変更しません','Original files are not changed','不会修改原文件','不會修改原始檔案','원본 파일은 변경하지 않습니다','No modifica los originales','Les fichiers originaux ne sont pas modifiés','Originaldateien bleiben unverändert','Os arquivos originais não são alterados'],
    ['変換結果を新しいファイルとして保存します。元ファイル名も引き継がず、','The result is saved as a new file. The original filename is replaced with ','结果将保存为新文件，原文件名也会替换为','結果會儲存為新檔案，原始檔名也會替換為','결과를 새 파일로 저장하며 원본 파일명도 ','El resultado se guarda como archivo nuevo y el nombre original se sustituye por ','Le résultat est enregistré dans un nouveau fichier et le nom d’origine est remplacé par ','Das Ergebnis wird neu gespeichert; der ursprüngliche Dateiname wird ersetzt durch ','O resultado é salvo como novo arquivo e o nome original é substituído por '],
    ['へ置き換えます。','.','。','。','로 바꿉니다.','.','.','.','.'],
    ['変換結果を新しいファイルとして保存します。元ファイル名も引き継がず、meta_zero へ置き換えます。','The result is saved as a new file. The original filename is replaced with meta_zero.','结果将保存为新文件，原文件名也会替换为meta_zero。','結果會儲存為新檔案，原始檔名也會替換為meta_zero。','결과를 새 파일로 저장하며 원본 파일명도 meta_zero로 바꿉니다.','El resultado se guarda como archivo nuevo y el nombre original se sustituye por meta_zero.','Le résultat est enregistré dans un nouveau fichier et le nom d’origine est remplacé par meta_zero.','Das Ergebnis wird neu gespeichert; der ursprüngliche Dateiname wird durch meta_zero ersetzt.','O resultado é salvo como novo arquivo e o nome original é substituído por meta_zero.'],
    ['完全ローカル処理','Fully local processing','完全本地处理','完全本機處理','완전 로컬 처리','Procesamiento totalmente local','Traitement entièrement local','Vollständig lokale Verarbeitung','Processamento totalmente local'],
    ['変換時にファイルや解析結果をサーバーへ送りません。外部フォントや解析ツールも読み込みません。','Files and analysis results are not sent to a server. No third-party fonts or analytics are loaded.','转换时不会向服务器发送文件或分析结果，也不会加载第三方字体或分析工具。','轉換時不會向伺服器傳送檔案或分析結果，也不會載入第三方字型或分析工具。','변환 중 파일이나 분석 결과를 서버로 보내지 않으며 외부 폰트나 분석 도구도 불러오지 않습니다.','No envía archivos ni resultados al servidor ni carga fuentes o analítica de terceros.','N’envoie ni fichiers ni résultats au serveur et ne charge ni polices ni outils d’analyse tiers.','Sendet weder Dateien noch Analysedaten und lädt keine externen Schriften oder Analysen.','Não envia arquivos nem resultados ao servidor e não carrega fontes ou análise de terceiros.'],
    ['色と形式について','Color and format notes','色彩与格式说明','色彩與格式說明','색상 및 형식 안내','Notas de color y formato','Notes sur la couleur et le format','Hinweise zu Farbe und Format','Notas de cor e formato'],
    ['ICCカラープロファイルも除去するため、環境によって色がわずかに変わる場合があります。アニメーションWebP／APNGとHEICは現在未対応です。','ICC color profiles are removed, so colors may vary slightly. Animated WebP/APNG and HEIC are not currently supported.','ICC色彩配置也会删除，因此颜色可能略有变化。目前不支持动画WebP/APNG和HEIC。','ICC色彩描述也會刪除，因此色彩可能略有差異。目前不支援動畫WebP/APNG與HEIC。','ICC 색상 프로필도 제거하므로 색이 약간 달라질 수 있습니다. 애니메이션 WebP/APNG와 HEIC는 지원하지 않습니다.','Los perfiles ICC se eliminan, por lo que el color puede variar. WebP/APNG animado y HEIC no son compatibles.','Les profils ICC sont supprimés, les couleurs peuvent donc varier. WebP/APNG animés et HEIC ne sont pas pris en charge.','ICC-Profile werden entfernt; Farben können leicht abweichen. Animiertes WebP/APNG und HEIC werden nicht unterstützt.','Perfis ICC são removidos, então as cores podem variar. WebP/APNG animado e HEIC não são suportados.'],
    ['3ステップで完了','Done in 3 steps','3步完成','3步完成','3단계로 완료','Listo en 3 pasos','Terminé en 3 étapes','In 3 Schritten fertig','Conclua em 3 etapas'],
    ['ファイルを選ぶ','Choose files','选择文件','選擇檔案','파일 선택','Elige archivos','Choisir les fichiers','Dateien auswählen','Escolha os arquivos'],
    ['画像は10件、動画は3件までまとめて選択できます。','Select up to 10 images or 3 videos at once.','一次最多选择10张图片或3个视频。','一次最多選擇10張圖片或3部影片。','이미지 10개 또는 동영상 3개까지 한 번에 선택할 수 있습니다.','Selecciona hasta 10 imágenes o 3 vídeos.','Sélectionnez jusqu’à 10 images ou 3 vidéos.','Wählen Sie bis zu 10 Bilder oder 3 Videos.','Selecione até 10 imagens ou 3 vídeos.'],
    ['端末内で変換','Convert locally','本地转换','本機轉換','기기 내 변환','Convierte localmente','Convertir localement','Lokal konvertieren','Converta localmente'],
    ['複数ある場合も1件ずつ処理し、完了した一時データから順に解放します。','Files are processed one by one and temporary work data is released as each finishes.','多个文件也会逐个处理，并依次释放已完成的临时数据。','多個檔案也會逐一處理，並依序釋放已完成的暫存資料。','여러 파일도 하나씩 처리하고 완료된 임시 데이터부터 해제합니다.','Los archivos se procesan uno a uno y se libera la memoria temporal al terminar.','Les fichiers sont traités un par un et les données temporaires libérées au fur et à mesure.','Dateien werden einzeln verarbeitet und temporäre Daten danach freigegeben.','Os arquivos são processados um por vez e os dados temporários liberados ao terminar.'],
    ['新しいファイルを保存','Save the new file','保存新文件','儲存新檔案','새 파일 저장','Guarda el nuevo archivo','Enregistrer le nouveau fichier','Neue Datei speichern','Salve o novo arquivo'],
    ['の名前で保存します。同名がある場合は端末側が重複名を付けます。','is used as the filename. Your device adds a duplicate suffix when needed.','作为文件名保存。如有同名文件，设备会添加重复编号。','作為檔名儲存。如有同名檔案，裝置會加入重複編號。','이름으로 저장하며 같은 이름이 있으면 기기가 중복 번호를 붙입니다.','se usa como nombre. Tu dispositivo añadirá un sufijo si ya existe.','est utilisé comme nom. Votre appareil ajoute un suffixe en cas de doublon.','wird als Name verwendet. Das Gerät ergänzt bei Bedarf eine Nummer.','é usado como nome. O dispositivo adiciona um sufixo quando necessário.'],
    ['種類','Type','类型','類型','종류','Tipo','Type','Typ','Tipo'],
    ['入力','Input','输入','輸入','입력','Entrada','Entrée','Eingabe','Entrada'],
    ['出力','Output','输出','輸出','출력','Salida','Sortie','Ausgabe','Saída'],
    ['件数','Limit','数量','數量','개수','Límite','Limite','Anzahl','Limite'],
    ['JPEG / PNG / 静止WebP','JPEG / PNG / static WebP','JPEG / PNG / 静态WebP','JPEG / PNG / 靜態WebP','JPEG / PNG / 정지 WebP','JPEG / PNG / WebP estático','JPEG / PNG / WebP statique','JPEG / PNG / statisches WebP','JPEG / PNG / WebP estático'],
    ['元形式を維持','Same format','保持原格式','維持原格式','원본 형식 유지','Mismo formato','Même format','Gleiches Format','Mesmo formato'],
    ['ブラウザ再生対応形式','Browser-playable formats','浏览器可播放格式','瀏覽器可播放格式','브라우저 재생 가능 형식','Formatos reproducibles','Formats lisibles par le navigateur','Im Browser abspielbare Formate','Formatos reproduzíveis no navegador'],
    ['WebM または MP4','WebM or MP4','WebM或MP4','WebM或MP4','WebM 또는 MP4','WebM o MP4','WebM ou MP4','WebM oder MP4','WebM ou MP4'],
    ['最大10件・64MP','Up to 10 · 64 MP','最多10个·64MP','最多10個·64MP','최대 10개·64MP','Hasta 10 · 64 MP','Jusqu’à 10 · 64 MP','Bis zu 10 · 64 MP','Até 10 · 64 MP'],
    ['最大3件・各1GB・4K相当','Up to 3 · 1 GB each · 4K','最多3个·每个1GB·4K','最多3個·每個1GB·4K','최대 3개·각 1GB·4K','Hasta 3 · 1 GB · 4K','Jusqu’à 3 · 1 Go · 4K','Bis zu 3 · je 1 GB · 4K','Até 3 · 1 GB cada · 4K'],
    ['処理中は種類を切り替えられません。','You cannot switch type while processing.','处理中无法切换类型。','處理中無法切換類型。','처리 중에는 종류를 바꿀 수 없습니다.','No puedes cambiar el tipo durante el proceso.','Impossible de changer de type pendant le traitement.','Während der Verarbeitung kann der Typ nicht gewechselt werden.','Não é possível trocar o tipo durante o processamento.'],
    ['待機中','Waiting','等待中','等待中','대기 중','En espera','En attente','Wartend','Aguardando'],
    ['保存','Save','保存','儲存','저장','Guardar','Enregistrer','Speichern','Salvar'],
    ['外す','Remove','移除','移除','제거','Quitar','Retirer','Entfernen','Remover'],
    ['画像を変換しています','Converting images','正在转换图片','正在轉換圖片','이미지 변환 중','Convirtiendo imágenes','Conversion des images','Bilder werden konvertiert','Convertendo imagens'],
    ['読み込んでいます…','Loading…','加载中…','載入中…','불러오는 중…','Cargando…','Chargement…','Laden…','Carregando…'],
    ['変換完了・埋め込み情報は検出されませんでした','Complete · no embedded metadata detected','完成·未检测到嵌入信息','完成·未偵測到嵌入資訊','완료·내장 정보가 감지되지 않음','Completado · no se detectaron metadatos','Terminé · aucune métadonnée détectée','Fertig · keine eingebetteten Metadaten erkannt','Concluído · nenhum metadado detectado'],
    ['変換完了・保存前に再確認してください','Complete · please verify before saving','完成·保存前请再次确认','完成·儲存前請再次確認','완료·저장 전에 다시 확인하세요','Completado · comprueba antes de guardar','Terminé · vérifiez avant d’enregistrer','Fertig · vor dem Speichern prüfen','Concluído · verifique antes de salvar'],
    ['画像の変換が完了しました','Image conversion complete','图片转换完成','圖片轉換完成','이미지 변환 완료','Conversión de imágenes completada','Conversion des images terminée','Bildkonvertierung abgeschlossen','Conversão de imagens concluída'],
    ['画像処理を中止しました。','Image processing cancelled.','图片处理已取消。','圖片處理已取消。','이미지 처리를 중지했습니다.','Proceso de imágenes cancelado.','Traitement des images annulé.','Bildverarbeitung abgebrochen.','Processamento de imagens cancelado.'],
    ['このブラウザでは動画の端末内再生成を利用できません。','This browser cannot regenerate video locally.','此浏览器无法在本地重建视频。','此瀏覽器無法在本機重建影片。','이 브라우저에서는 동영상 로컬 재생성을 사용할 수 없습니다.','Este navegador no puede regenerar vídeo localmente.','Ce navigateur ne peut pas régénérer la vidéo localement.','Dieser Browser kann Videos nicht lokal neu erzeugen.','Este navegador não pode regenerar vídeo localmente.'],
    ['動画を変換しています','Converting videos','正在转换视频','正在轉換影片','동영상 변환 중','Convirtiendo vídeos','Conversion des vidéos','Videos werden konvertiert','Convertendo vídeos'],
    ['動画を準備しています…','Preparing video…','正在准备视频…','正在準備影片…','동영상 준비 중…','Preparando vídeo…','Préparation de la vidéo…','Video wird vorbereitet…','Preparando vídeo…'],
    ['変換完了・指定した保存先へ保存しました','Complete · saved to the selected location','完成·已保存到指定位置','完成·已儲存到指定位置','완료·지정한 위치에 저장됨','Completado · guardado en la ubicación elegida','Terminé · enregistré à l’emplacement choisi','Fertig · am gewählten Ort gespeichert','Concluído · salvo no local escolhido'],
    ['変換完了・元の埋め込み情報を引き継がず再生成しました','Complete · regenerated without carrying over original metadata','完成·已重建且未继承原始元数据','完成·已重建且未繼承原始中繼資料','완료·원본 내장 정보를 이어받지 않고 재생성됨','Completado · regenerado sin conservar metadatos originales','Terminé · régénéré sans conserver les métadonnées d’origine','Fertig · ohne ursprüngliche Metadaten neu erzeugt','Concluído · regenerado sem manter metadados originais'],
    ['動画の変換が完了しました','Video conversion complete','视频转换完成','影片轉換完成','동영상 변환 완료','Conversión de vídeo completada','Conversion vidéo terminée','Videokonvertierung abgeschlossen','Conversão de vídeo concluída'],
    ['動画処理を中止しました。','Video processing cancelled.','视频处理已取消。','影片處理已取消。','동영상 처리를 중지했습니다.','Proceso de vídeo cancelado.','Traitement vidéo annulé.','Videoverarbeitung abgebrochen.','Processamento de vídeo cancelado.'],
    ['このブラウザは動画の端末内再生成に未対応です。最新版のChromeまたはEdgeをお試しください。','This browser does not support local video regeneration. Try the latest Chrome or Edge.','此浏览器不支持本地视频重建，请尝试最新版Chrome或Edge。','此瀏覽器不支援本機影片重建，請嘗試最新版Chrome或Edge。','이 브라우저는 동영상 로컬 재생성을 지원하지 않습니다. 최신 Chrome 또는 Edge를 사용하세요.','Este navegador no admite la regeneración local de vídeo. Prueba Chrome o Edge actualizados.','Ce navigateur ne prend pas en charge la régénération locale. Essayez Chrome ou Edge à jour.','Dieser Browser unterstützt keine lokale Videoneuerzeugung. Nutzen Sie aktuelles Chrome oder Edge.','Este navegador não suporta regeneração local de vídeo. Use Chrome ou Edge atualizado.'],
    ['動画変換に対応しています。300MB超は保存先へ直接書き込む大容量モードを使用できます。','Video conversion is supported. Files over 300 MB can use direct-to-disk Large File Mode.','支持视频转换，超过300MB可使用直接写入保存位置的大文件模式。','支援影片轉換，超過300MB可使用直接寫入儲存位置的大檔案模式。','동영상 변환을 지원합니다. 300MB 초과 파일은 저장 위치에 직접 쓰는 대용량 모드를 사용할 수 있습니다.','Conversión compatible. Los archivos de más de 300 MB pueden guardarse directamente.','Conversion prise en charge. Les fichiers de plus de 300 Mo peuvent être écrits directement.','Videokonvertierung unterstützt. Dateien über 300 MB können direkt gespeichert werden.','Conversão compatível. Arquivos acima de 300 MB podem ser gravados diretamente.'],
    ['動画変換に対応しています。この端末では300MB以下の動画を推奨します。','Video conversion is supported. Videos under 300 MB are recommended on this device.','支持视频转换，建议在此设备上使用300MB以下的视频。','支援影片轉換，建議在此裝置上使用300MB以下的影片。','동영상 변환을 지원합니다. 이 기기에서는 300MB 이하를 권장합니다.','Conversión compatible. Se recomiendan vídeos de menos de 300 MB.','Conversion prise en charge. Les vidéos de moins de 300 Mo sont recommandées.','Videokonvertierung unterstützt. Videos unter 300 MB werden empfohlen.','Conversão compatível. Recomendamos vídeos abaixo de 300 MB.'],
    ['JPEG・PNG・WebP以外の画像は追加できません。','Only JPEG, PNG and WebP images can be added.','只能添加JPEG、PNG和WebP图片。','只能加入JPEG、PNG與WebP圖片。','JPEG, PNG, WebP 이미지만 추가할 수 있습니다.','Solo se admiten imágenes JPEG, PNG y WebP.','Seules les images JPEG, PNG et WebP sont acceptées.','Nur JPEG-, PNG- und WebP-Bilder sind möglich.','Apenas imagens JPEG, PNG e WebP são aceitas.'],
    ['動画として認識できないファイルを除外しました。','Files not recognized as video were skipped.','已跳过无法识别为视频的文件。','已略過無法辨識為影片的檔案。','동영상으로 인식되지 않는 파일을 제외했습니다.','Se omitieron archivos no reconocidos como vídeo.','Les fichiers non reconnus comme vidéo ont été ignorés.','Nicht als Video erkannte Dateien wurden übersprungen.','Arquivos não reconhecidos como vídeo foram ignorados.'],
    ['1GBを超える動画は追加できません。','Videos larger than 1 GB cannot be added.','无法添加超过1GB的视频。','無法加入超過1GB的影片。','1GB를 넘는 동영상은 추가할 수 없습니다.','No se admiten vídeos de más de 1 GB.','Les vidéos de plus de 1 Go ne sont pas acceptées.','Videos über 1 GB können nicht hinzugefügt werden.','Vídeos acima de 1 GB não são aceitos.'],
    ['アニメーションWebP／APNGは現在未対応です。','Animated WebP/APNG is not currently supported.','目前不支持动画WebP/APNG。','目前不支援動畫WebP/APNG。','애니메이션 WebP/APNG는 현재 지원하지 않습니다.','WebP/APNG animado no es compatible.','WebP/APNG animé n’est pas pris en charge.','Animiertes WebP/APNG wird nicht unterstützt.','WebP/APNG animado não é suportado.'],
    ['安全に中止しています…','Stopping safely…','正在安全停止…','正在安全停止…','안전하게 중지 중…','Deteniendo de forma segura…','Arrêt sécurisé…','Wird sicher beendet…','Interrompendo com segurança…'],
    ['画像サイズを取得できません。','Could not determine the image dimensions.','无法获取图片尺寸。','無法取得圖片尺寸。','이미지 크기를 확인할 수 없습니다.','No se pudo obtener el tamaño de la imagen.','Impossible de déterminer les dimensions de l’image.','Bildgröße konnte nicht ermittelt werden.','Não foi possível obter as dimensões da imagem.'],
    ['64メガピクセルを超える画像には対応していません。','Images over 64 megapixels are not supported.','不支持超过6400万像素的图片。','不支援超過6400萬像素的圖片。','6400만 픽셀을 넘는 이미지는 지원하지 않습니다.','No se admiten imágenes de más de 64 megapíxeles.','Les images de plus de 64 mégapixels ne sont pas prises en charge.','Bilder über 64 Megapixel werden nicht unterstützt.','Imagens acima de 64 megapixels não são suportadas.'],
    ['この端末では画像を処理できません。','This device cannot process the image.','此设备无法处理该图片。','此裝置無法處理該圖片。','이 기기에서는 이미지를 처리할 수 없습니다.','Este dispositivo no puede procesar la imagen.','Cet appareil ne peut pas traiter l’image.','Dieses Gerät kann das Bild nicht verarbeiten.','Este dispositivo não pode processar a imagem.'],
    ['300MBを超える動画は、PC版ChromeまたはEdgeの大容量モードが必要です。','Videos over 300 MB require Large File Mode in desktop Chrome or Edge.','超过300MB的视频需要桌面版Chrome或Edge的大文件模式。','超過300MB的影片需要桌面版Chrome或Edge的大檔案模式。','300MB를 넘는 동영상은 PC용 Chrome 또는 Edge의 대용량 모드가 필요합니다.','Los vídeos de más de 300 MB requieren el modo de archivo grande en Chrome o Edge para PC.','Les vidéos de plus de 300 Mo nécessitent le mode grande taille de Chrome ou Edge sur PC.','Videos über 300 MB benötigen den Großdateimodus in Chrome oder Edge für PC.','Vídeos acima de 300 MB exigem o modo de arquivo grande no Chrome ou Edge para PC.'],
    ['動画情報を読み込めませんでした。','Could not read the video information.','无法读取视频信息。','無法讀取影片資訊。','동영상 정보를 읽을 수 없습니다.','No se pudo leer la información del vídeo.','Impossible de lire les informations de la vidéo.','Videoinformationen konnten nicht gelesen werden.','Não foi possível ler as informações do vídeo.'],
    ['動画の再生時間を取得できません。','Could not determine the video duration.','无法获取视频时长。','無法取得影片時長。','동영상 재생 시간을 확인할 수 없습니다.','No se pudo obtener la duración del vídeo.','Impossible de déterminer la durée de la vidéo.','Videodauer konnte nicht ermittelt werden.','Não foi possível obter a duração do vídeo.'],
    ['映像トラックが見つかりません。','No video track was found.','未找到视频轨道。','找不到影像軌。','영상 트랙을 찾을 수 없습니다.','No se encontró una pista de vídeo.','Aucune piste vidéo trouvée.','Keine Videospur gefunden.','Nenhuma faixa de vídeo foi encontrada.'],
    ['現在は4K相当を超える動画には対応していません。','Videos above approximately 4K are not currently supported.','目前不支持超过约4K的视频。','目前不支援超過約4K的影片。','현재 약 4K를 넘는 동영상은 지원하지 않습니다.','Actualmente no se admiten vídeos superiores a aproximadamente 4K.','Les vidéos supérieures à environ 4K ne sont pas prises en charge.','Videos über ungefähr 4K werden derzeit nicht unterstützt.','Vídeos acima de aproximadamente 4K não são suportados.'],
    ['このブラウザでは映像を再生成できません。','This browser cannot regenerate video.','此浏览器无法重建视频。','此瀏覽器無法重新產生影片。','이 브라우저에서는 영상을 재생성할 수 없습니다.','Este navegador no puede regenerar vídeo.','Ce navigateur ne peut pas régénérer la vidéo.','Dieser Browser kann Videos nicht neu erzeugen.','Este navegador não pode regenerar vídeo.'],
    ['動画の出力に失敗しました。','Video output failed.','视频输出失败。','影片輸出失敗。','동영상 출력에 실패했습니다.','No se pudo generar el vídeo.','Échec de la création de la vidéo.','Videoausgabe fehlgeschlagen.','Falha ao gerar o vídeo.'],
    ['画像の再生成に失敗しました。','Image regeneration failed.','图片重建失败。','圖片重新產生失敗。','이미지 재생성에 실패했습니다.','No se pudo regenerar la imagen.','Échec de la régénération de l’image.','Bilderzeugung fehlgeschlagen.','Falha ao regenerar a imagem.'],
    ['保存先の選択がキャンセルされました。','Save location selection was cancelled.','已取消选择保存位置。','已取消選擇儲存位置。','저장 위치 선택이 취소되었습니다.','Se canceló la selección del destino.','La sélection de l’emplacement a été annulée.','Die Auswahl des Speicherorts wurde abgebrochen.','A seleção do local de salvamento foi cancelada.'],
    ['端末の空き容量が不足しています。','Not enough free storage is available.','设备可用存储空间不足。','裝置可用儲存空間不足。','기기의 여유 공간이 부족합니다.','No hay suficiente espacio libre en el dispositivo.','Espace libre insuffisant sur l’appareil.','Nicht genügend freier Speicherplatz auf dem Gerät.','Não há espaço livre suficiente no dispositivo.'],
    ['処理中にエラーが発生しました。','An error occurred during processing.','处理时发生错误。','處理時發生錯誤。','처리 중 오류가 발생했습니다.','Ocurrió un error durante el proceso.','Une erreur est survenue pendant le traitement.','Bei der Verarbeitung ist ein Fehler aufgetreten.','Ocorreu um erro durante o processamento.']
  ];

  const dictionaries = Object.fromEntries(languages.map((language, index) => [language, Object.fromEntries(rows.map(row => [row[0], row[index]]))]));
  const originalText = new WeakMap();
  const originalAttrs = new WeakMap();
  let current = 'ja';

  const dynamicPatterns = {
    en: [[/^(\d+)件追加しました。$/, '$1 file(s) added.'],[/^(\d+)件を超えたファイルは追加していません。$/, 'Files beyond the $1-file limit were not added.'],[/^(\d+)件の画像を変換しました。$/, '$1 image(s) converted.'],[/^(\d+)件の動画を変換しました。$/, '$1 video(s) converted.'],[/^(\d+)件の保存を開始しました。$/, 'Started saving $1 file(s).'],[/^(\d+)\/(\d+)件を保存できます。$/, '$1/$2 file(s) are ready to save.'],[/^(\d+)\/(\d+)件が完了しました。$/, '$1/$2 file(s) completed.'],[/^画像 (\d+)\/(\d+)$/, 'Image $1/$2'],[/^動画 (\d+)\/(\d+)$/, 'Video $1/$2'],[/^変換済みを保存（(\d+)件）$/, 'Save converted files ($1)'],[/^端末由来の特徴を弱めています… (\d+)%$/, 'Reducing device-derived patterns… $1%'],[/^(\d+:\d{2}) \/ (\d+:\d{2}) — 再生しながら端末内で再生成中$/, '$1 / $2 — regenerating locally during playback']],
    'zh-CN': [[/^(\d+)件追加しました。$/, '已添加$1个文件。'],[/^(\d+)件を超えたファイルは追加していません。$/, '超过$1个的文件未添加。'],[/^(\d+)件の画像を変換しました。$/, '已转换$1张图片。'],[/^(\d+)件の動画を変換しました。$/, '已转换$1个视频。'],[/^(\d+)件の保存を開始しました。$/, '已开始保存$1个文件。'],[/^(\d+)\/(\d+)件を保存できます。$/, '$1/$2个文件可保存。'],[/^(\d+)\/(\d+)件が完了しました。$/, '已完成$1/$2个文件。'],[/^画像 (\d+)\/(\d+)$/, '图片 $1/$2'],[/^動画 (\d+)\/(\d+)$/, '视频 $1/$2'],[/^変換済みを保存（(\d+)件）$/, '保存已转换文件（$1）'],[/^端末由来の特徴を弱めています… (\d+)%$/, '正在弱化设备来源特征… $1%'],[/^(\d+:\d{2}) \/ (\d+:\d{2}) — 再生しながら端末内で再生成中$/, '$1 / $2 — 正在播放并在设备内重建']],
    'zh-TW': [[/^(\d+)件追加しました。$/, '已加入$1個檔案。'],[/^(\d+)件を超えたファイルは追加していません。$/, '超過$1個的檔案未加入。'],[/^(\d+)件の画像を変換しました。$/, '已轉換$1張圖片。'],[/^(\d+)件の動画を変換しました。$/, '已轉換$1部影片。'],[/^(\d+)件の保存を開始しました。$/, '已開始儲存$1個檔案。'],[/^(\d+)\/(\d+)件を保存できます。$/, '$1/$2個檔案可儲存。'],[/^(\d+)\/(\d+)件が完了しました。$/, '已完成$1/$2個檔案。'],[/^画像 (\d+)\/(\d+)$/, '圖片 $1/$2'],[/^動画 (\d+)\/(\d+)$/, '影片 $1/$2'],[/^変換済みを保存（(\d+)件）$/, '儲存已轉換檔案（$1）'],[/^端末由来の特徴を弱めています… (\d+)%$/, '正在弱化裝置來源特徵… $1%'],[/^(\d+:\d{2}) \/ (\d+:\d{2}) — 再生しながら端末内で再生成中$/, '$1 / $2 — 正在播放並於裝置內重新產生']],
    ko: [[/^(\d+)件追加しました。$/, '$1개 파일을 추가했습니다.'],[/^(\d+)件を超えたファイルは追加していません。$/, '$1개를 초과한 파일은 추가하지 않았습니다.'],[/^(\d+)件の画像を変換しました。$/, '이미지 $1개를 변환했습니다.'],[/^(\d+)件の動画を変換しました。$/, '동영상 $1개를 변환했습니다.'],[/^(\d+)件の保存を開始しました。$/, '$1개 파일 저장을 시작했습니다.'],[/^(\d+)\/(\d+)件を保存できます。$/, '$1/$2개 파일을 저장할 수 있습니다.'],[/^(\d+)\/(\d+)件が完了しました。$/, '$1/$2개 파일이 완료되었습니다.'],[/^画像 (\d+)\/(\d+)$/, '이미지 $1/$2'],[/^動画 (\d+)\/(\d+)$/, '동영상 $1/$2'],[/^変換済みを保存（(\d+)件）$/, '변환 파일 저장 ($1개)'],[/^端末由来の特徴を弱めています… (\d+)%$/, '기기 유래 특징 약화 중… $1%'],[/^(\d+:\d{2}) \/ (\d+:\d{2}) — 再生しながら端末内で再生成中$/, '$1 / $2 — 재생하면서 기기 안에서 재생성 중']],
    es: [[/^(\d+)件追加しました。$/, '$1 archivo(s) añadido(s).'],[/^(\d+)件を超えたファイルは追加していません。$/, 'No se añadieron archivos que superaban el límite de $1.'],[/^(\d+)件の画像を変換しました。$/, '$1 imagen(es) convertida(s).'],[/^(\d+)件の動画を変換しました。$/, '$1 vídeo(s) convertido(s).'],[/^(\d+)件の保存を開始しました。$/, 'Guardando $1 archivo(s).'],[/^(\d+)\/(\d+)件を保存できます。$/, '$1/$2 archivo(s) listos para guardar.'],[/^(\d+)\/(\d+)件が完了しました。$/, '$1/$2 archivo(s) completados.'],[/^画像 (\d+)\/(\d+)$/, 'Imagen $1/$2'],[/^動画 (\d+)\/(\d+)$/, 'Vídeo $1/$2'],[/^変換済みを保存（(\d+)件）$/, 'Guardar convertidos ($1)'],[/^端末由来の特徴を弱めています… (\d+)%$/, 'Reduciendo patrones del dispositivo… $1%'],[/^(\d+:\d{2}) \/ (\d+:\d{2}) — 再生しながら端末内で再生成中$/, '$1 / $2 — regenerando localmente durante la reproducción']],
    fr: [[/^(\d+)件追加しました。$/, '$1 fichier(s) ajouté(s).'],[/^(\d+)件を超えたファイルは追加していません。$/, 'Les fichiers au-delà de la limite de $1 n’ont pas été ajoutés.'],[/^(\d+)件の画像を変換しました。$/, '$1 image(s) convertie(s).'],[/^(\d+)件の動画を変換しました。$/, '$1 vidéo(s) convertie(s).'],[/^(\d+)件の保存を開始しました。$/, 'Enregistrement de $1 fichier(s).'],[/^(\d+)\/(\d+)件を保存できます。$/, '$1/$2 fichier(s) prêts à être enregistrés.'],[/^(\d+)\/(\d+)件が完了しました。$/, '$1/$2 fichier(s) terminés.'],[/^画像 (\d+)\/(\d+)$/, 'Image $1/$2'],[/^動画 (\d+)\/(\d+)$/, 'Vidéo $1/$2'],[/^変換済みを保存（(\d+)件）$/, 'Enregistrer ($1)'],[/^端末由来の特徴を弱めています… (\d+)%$/, 'Réduction des signatures… $1%'],[/^(\d+:\d{2}) \/ (\d+:\d{2}) — 再生しながら端末内で再生成中$/, '$1 / $2 — régénération locale pendant la lecture']],
    de: [[/^(\d+)件追加しました。$/, '$1 Datei(en) hinzugefügt.'],[/^(\d+)件を超えたファイルは追加していません。$/, 'Dateien über dem Limit von $1 wurden nicht hinzugefügt.'],[/^(\d+)件の画像を変換しました。$/, '$1 Bild(er) konvertiert.'],[/^(\d+)件の動画を変換しました。$/, '$1 Video(s) konvertiert.'],[/^(\d+)件の保存を開始しました。$/, '$1 Datei(en) werden gespeichert.'],[/^(\d+)\/(\d+)件を保存できます。$/, '$1/$2 Datei(en) können gespeichert werden.'],[/^(\d+)\/(\d+)件が完了しました。$/, '$1/$2 Datei(en) abgeschlossen.'],[/^画像 (\d+)\/(\d+)$/, 'Bild $1/$2'],[/^動画 (\d+)\/(\d+)$/, 'Video $1/$2'],[/^変換済みを保存（(\d+)件）$/, 'Konvertierte speichern ($1)'],[/^端末由来の特徴を弱めています… (\d+)%$/, 'Gerätemuster werden reduziert… $1%'],[/^(\d+:\d{2}) \/ (\d+:\d{2}) — 再生しながら端末内で再生成中$/, '$1 / $2 — lokale Neuerzeugung während der Wiedergabe']],
    pt: [[/^(\d+)件追加しました。$/, '$1 arquivo(s) adicionado(s).'],[/^(\d+)件を超えたファイルは追加していません。$/, 'Arquivos acima do limite de $1 não foram adicionados.'],[/^(\d+)件の画像を変換しました。$/, '$1 imagem(ns) convertida(s).'],[/^(\d+)件の動画を変換しました。$/, '$1 vídeo(s) convertido(s).'],[/^(\d+)件の保存を開始しました。$/, 'Salvando $1 arquivo(s).'],[/^(\d+)\/(\d+)件を保存できます。$/, '$1/$2 arquivo(s) prontos para salvar.'],[/^(\d+)\/(\d+)件が完了しました。$/, '$1/$2 arquivo(s) concluídos.'],[/^画像 (\d+)\/(\d+)$/, 'Imagem $1/$2'],[/^動画 (\d+)\/(\d+)$/, 'Vídeo $1/$2'],[/^変換済みを保存（(\d+)件）$/, 'Salvar convertidos ($1)'],[/^端末由来の特徴を弱めています… (\d+)%$/, 'Reduzindo padrões do dispositivo… $1%'],[/^(\d+:\d{2}) \/ (\d+:\d{2}) — 再生しながら端末内で再生成中$/, '$1 / $2 — regenerando localmente durante a reprodução']]
  };

  function normalizeLanguage(value) {
    if (languages.includes(value)) return value;
    const lower = String(value || '').toLowerCase();
    if (lower.startsWith('zh-tw') || lower.startsWith('zh-hk')) return 'zh-TW';
    if (lower.startsWith('zh')) return 'zh-CN';
    return languages.find(language => lower.startsWith(language.toLowerCase())) || 'ja';
  }

  function translate(value, language = current) {
    const source = String(value ?? '');
    if (language === 'ja') return source;
    const exact = dictionaries[language]?.[source];
    if (exact) return exact;
    for (const [pattern, replacement] of dynamicPatterns[language] || []) {
      if (pattern.test(source)) return source.replace(pattern, replacement);
    }
    return source;
  }

  function translateDom(language) {
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(node => {
      if (node.parentElement?.closest('#languageSelect,script,style')) return;
      if (!originalText.has(node)) originalText.set(node, node.nodeValue);
      const original = originalText.get(node);
      const trimmed = original.trim();
      if (!trimmed) return;
      const translated = translate(trimmed, language);
      node.nodeValue = original.replace(trimmed, translated);
    });
    document.querySelectorAll('[aria-label], [title]').forEach(element => {
      if (!originalAttrs.has(element)) originalAttrs.set(element, { aria: element.getAttribute('aria-label'), title: element.getAttribute('title') });
      const saved = originalAttrs.get(element);
      if (saved.aria) element.setAttribute('aria-label', translate(saved.aria, language));
      if (saved.title) element.setAttribute('title', translate(saved.title, language));
    });
    document.documentElement.lang = language;
    document.title = translate('META ZERO | eye-factory', language);
  }

  function setLanguage(language, persist = true) {
    current = normalizeLanguage(language);
    if (persist) localStorage.setItem('metaZeroLanguage', current);
    const select = document.getElementById('languageSelect');
    if (select) select.value = current;
    translateDom(current);
    window.dispatchEvent(new CustomEvent('metazero:languagechange', { detail: { language: current } }));
  }

  function initialLanguage() {
    return normalizeLanguage(localStorage.getItem('metaZeroLanguage') || navigator.language || 'ja');
  }

  window.MetaZeroI18n = { translate, setLanguage, getLanguage: () => current, languages };
  window.addEventListener('DOMContentLoaded', () => {
    const select = document.getElementById('languageSelect');
    select?.addEventListener('change', event => setLanguage(event.target.value));
    setLanguage(initialLanguage(), false);
  });
})();
