/* Copyright (c) 2026 eye-factory — https://eye-factory.net/ */
/* A small version overlay keeps the existing translated manual and assets intact. */
window.MultinaManualApplyV102 = bundle => {
  const copy={
    ja:{title:'v1.0.2：カスタム登録の共有と新しい操作',online:'Multinaの動画・画像・画面録画・漫画とAI連携のWeb取扱説明書。インターネット接続が必要です。',
      share:['上部の「エクスポート」で「プロジェクト／作品」または「カスタム登録のみ」を選びます。カスタム登録は、この編集ツールの全登録を .multinacustom にまとめます。','動画は素材・設定・追加フォント、画像はカスタム素材・保存レイヤー・文字登録と必要なフォント、漫画は追加ペンの設定とペン先を含めます。作品や作品へ取り込んだだけの素材は含みません。','上部の「インポート」で共有ファイルを選ぶと、内容から編集ツールの種類を自動判別します。既存登録を置き換えず追加し、作品は変更しません。同名は番号を付けます。漫画ペンの呼び出しキーは読み込み後に再設定してください。','共有が許可された素材・フォントだけを配布してください。書き出し先には作品・登録の管理フォルダー以外を選びます。登録は1回10000件・同梱素材は合計64GiBまで、追加ペンは既存分を含め128件までです。','説明書ボタンと配布ファイルの1_Multina_Manual.htmlは、このWeb説明書を開きます。アプリからはアプリの言語、配布ファイルからはブラウザーの言語に合わせます。インターネット接続が必要です。'],
      video:['レイヤーの右クリックから追加するテキスト・モザイク・ブラーは、マウスの場所ではなくタイムラインの再生バー位置に作られます。','初期設定のRは、カーソルが有限の空間上にあれば他のクリップが選択中でも空間を優先します。「このトラックだけ」「全トラック」から選ぶまで素材は動きません。ロック中・クリップ上・最後の素材以降の無限の空白は対象外です。','再生バーを左右端へドラッグすると、バーを見える位置に保ちながらスクロールします。素材がなくてもタイムラインの実際の端まで進められます。','書き出し進捗は整数の目安です。実際に進んだ処理を反映し、処理が進んでいる間は約10秒ごとにも更新します。時間だけで増やさず、完了前は100%になりません。処理量によって数値が一度に変わる場合があります。'],
      importVideo:'編集用作品の読み込みでは、.veprojectフォルダー内のproject.jsonを選びます。project.jsonと素材は同じフォルダー構成のまま丸ごと保管してください。',
      image:['囲みエフェクトの種類をモザイク／ブラーへ変更すると、設定表示と自動のレイヤー名が連動します。自分で付けたレイヤー名は変更しません。','カスタム登録の共有には、カスタム素材・保存レイヤー・文字スタイルと追加フォントを含められます。上部のエクスポートで「カスタム登録のみ」を選びます。'],
      comic:['楕円の右にあるモザイク／ブラーを選び、編集可能で表示中のレイヤーを選んでキャンバスをドラッグします。元の絵を変更せず、選んだレイヤーの上へ範囲エフェクトを追加します。','下のレイヤーの合成結果へ適用します。種類・強さ・位置・サイズ・回転・不透明度は要素設定で調整します。消しゴム・クリッピング・Undo/Redo・保存・PNG/PDF出力にも対応します。','レイヤーのfxで効果だけをON/OFFできます。下の絵を参照するため、この範囲エフェクトの単独ラスタライズや下との結合はできません。完成画像は通常の画像書き出しを使ってください。','追加ペンをまとめて共有する場合は、上部のエクスポートで「カスタム登録のみ」を選びます。読み込み後にペンの呼び出しキーを再設定してください。']},
    en:{title:'v1.0.2: Share custom libraries and new controls',online:'Online manual for Multina video, image, recording, comics and AI integration. An internet connection is required.',
      share:['From the top Export button, choose Project / artwork or Custom registrations only. The latter saves all registrations for the current editor in one .multinacustom file.','Video includes registered media, settings and added fonts. Image includes custom assets, saved layers, text styles and required fonts. Comics includes added pen settings and tips. Projects and media imported only into a project are excluded.','Choose the shared file with the top Import button. Its contents identify the editor automatically. Existing entries are not replaced, projects are untouched, and duplicate names receive a suffix. Reassign imported comic pen shortcut keys.','Share only media and fonts you have permission to distribute. Save outside managed project/library folders. Limits: 10,000 registrations and 64GiB of resources per transfer; 128 added comic pens including existing ones.','The manual button and 1_Multina_Manual.html open this online manual. The app uses its selected language; the file uses your browser language. An internet connection is required.'],
      video:['Text, Mosaic and Blur from the layer context menu are created at the timeline playhead, not the mouse position.','With the default R shortcut, the finite gap under the cursor takes priority over a selected clip. Nothing moves until you choose this track or all tracks. Locked tracks, occupied clips and the empty tail after the last clip are excluded.','Dragging the playhead beyond either edge scrolls while keeping it visible, all the way to the actual timeline boundary, including blank space.','Export uses estimated whole-number progress based on advancing work, including roughly ten-second updates while work advances. Time alone never increases it; 100% is reserved for completion. Changes can still jump with varying workloads.'],
      importVideo:'To import editable video work, select project.json inside the .veproject folder. Keep the entire folder and its resource layout together.',
      image:['Switching a region effect between Mosaic and Blur updates its settings label and automatic layer name. Your own layer names are preserved.','Share custom assets, saved layers, text styles and added fonts by choosing Custom registrations only from the top Export button.'],
      comic:['Choose Mosaic or Blur after Ellipse, select an editable visible layer, then drag on the canvas. A region effect is added above that layer without changing the original art.','It affects the composite below. Adjust type, strength, position, size, rotation and opacity in object settings. Erasing, clipping, Undo/Redo, saving and PNG/PDF output are supported.','The layer fx switch toggles the effect. Because it depends on the artwork below, it cannot be rasterized alone or merged down. Use normal image export for the finished result.','For all added pens, choose Custom registrations only from the top Export button. Reassign pen shortcut keys after importing.']},
    de:{title:'v1.0.2: Vorlagen teilen und neue Bedienung',online:'Online-Handbuch für Multinas Video-, Bild-, Aufnahme-, Comic- und KI-Funktionen. Eine Internetverbindung ist nötig.',
      share:['Oben unter Export wählst du Projekt / Werk oder Nur eigene Vorlagen. Alle Vorlagen des aktuellen Editors werden als .multinacustom gespeichert.','Video enthält Medien, Einstellungen und zusätzliche Schriften; Bild enthält eigene Materialien, gespeicherte Ebenen, Textstile und nötige Schriften; Comic enthält eigene Stifte mit Spitzen. Projekte und reine Projektimporte sind nicht enthalten.','Import erkennt den Editor anhand der Datei. Vorhandene Einträge und Projekte bleiben unverändert; gleiche Namen erhalten eine Nummer. Weise importierten Comic-Stiften neue Tastenkürzel zu.','Teile nur Materialien und Schriften, die du weitergeben darfst. Speichere außerhalb verwalteter Ordner. Maximal 10000 Einträge und 64GiB pro Übertragung; insgesamt 128 zusätzliche Comic-Stifte.','Die Handbuch-Schaltfläche und 1_Multina_Manual.html öffnen dieses Online-Handbuch in der App- bzw. Browsersprache. Eine Internetverbindung ist erforderlich.'],
      video:['Text, Mosaik und Weichzeichnen im Ebenen-Kontextmenü entstehen am Abspielkopf, nicht an der Mausposition.','Die Standardtaste R bevorzugt die begrenzte Lücke unter dem Zeiger, auch bei ausgewähltem Clip. Erst die Wahl dieser/aller Spuren verschiebt Inhalte. Gesperrte Spuren, Clips und die freie Fläche nach dem letzten Clip sind ausgenommen.','Am linken und rechten Rand bleibt der gezogene Abspielkopf beim Scrollen sichtbar. Auch leere Bereiche bis zur tatsächlichen Zeitachsengrenze sind erreichbar.','Der Export zeigt geschätzte ganze Prozentwerte anhand tatsächlich fortschreitender Arbeit, bei Aktivität auch etwa alle zehn Sekunden. Zeit allein erhöht den Wert nicht; 100% bedeutet abgeschlossen. Größere Sprünge bleiben möglich.'],
      importVideo:'Wähle zum Projektimport project.json im .veproject-Ordner. Bewahre den ganzen Ordner einschließlich seiner Materialien zusammen auf.',
      image:['Mosaik/Weichzeichnen aktualisiert Einstellungsanzeige und automatischen Ebenennamen. Eigene Namen bleiben erhalten.','Wähle Nur eigene Vorlagen unter Export, um Materialien, gespeicherte Ebenen, Textstile und zusätzliche Schriften zu teilen.'],
      comic:['Mosaik/Weichzeichnen steht hinter Ellipse. Wähle eine sichtbare bearbeitbare Ebene und ziehe auf der Zeichenfläche. Der Effekt wird darüber angelegt; das Original bleibt unverändert.','Er wirkt auf die darunterliegende Gesamtzeichnung. Typ, Stärke, Position, Größe, Drehung und Deckkraft sind einstellbar. Radieren, Clipping, Undo/Redo, Speichern und PNG/PDF werden unterstützt.','fx schaltet den Effekt um. Da er die Zeichnung darunter benötigt, sind einzelnes Rastern und Zusammenfügen nach unten ausgeschlossen. Nutze den normalen Bildexport.','Teile zusätzliche Stifte über Nur eigene Vorlagen. Weise nach dem Import ihre Tastenkürzel neu zu.']},
    fr:{title:'v1.0.2 : Partage des préréglages et nouvelles commandes',online:'Manuel en ligne des outils vidéo, image, capture, BD et IA de Multina. Une connexion Internet est nécessaire.',
      share:['Le bouton Exporter en haut propose Projet / création ou Préréglages personnels uniquement. Tous les enregistrements de cet éditeur sont regroupés dans un fichier .multinacustom.','Vidéo : médias, réglages et polices ajoutées. Image : matériaux, calques enregistrés, styles de texte et polices nécessaires. BD : réglages et pointes des stylos ajoutés. Les projets et leurs simples médias importés sont exclus.','Importer reconnaît l’éditeur grâce au contenu. Les entrées existantes et les projets restent intacts ; les noms identiques reçoivent un numéro. Réattribuez les raccourcis des stylos importés.','Partagez uniquement les médias et polices dont la redistribution est autorisée. Enregistrez hors des dossiers gérés. Limites : 10000 entrées et 64GiB par transfert ; 128 stylos ajoutés au total.','Le bouton du manuel et 1_Multina_Manual.html ouvrent ce manuel en ligne, dans la langue de l’application ou du navigateur. Internet est nécessaire.'],
      video:['Texte, Mosaïque et Flou du menu contextuel des calques sont créés à la tête de lecture, pas au pointeur.','Le raccourci R par défaut privilégie l’espace délimité sous le pointeur même si un clip est sélectionné. Rien ne bouge avant de choisir cette piste ou toutes les pistes. Les pistes verrouillées, clips et espaces après le dernier clip sont exclus.','Le défilement aux deux bords garde la tête de lecture visible et atteint les limites réelles, y compris les zones vides.','La progression entière est estimée à partir du travail réel, avec des mises à jour environ toutes les dix secondes pendant l’activité. Le temps seul ne l’augmente pas ; 100% est réservé à la fin. Des sauts restent possibles.'],
      importVideo:'Pour importer un projet vidéo, choisissez project.json dans le dossier .veproject. Conservez le dossier entier avec ses ressources.',
      image:['Mosaïque/Flou met à jour le libellé et le nom automatique du calque, sans modifier les noms personnalisés.','Exportez matériaux, calques enregistrés, styles et polices ajoutées avec Préréglages personnels uniquement.'],
      comic:['Mosaïque/Flou se trouve après Ellipse. Sélectionnez un calque visible modifiable et faites glisser sur le canevas. L’effet est ajouté au-dessus sans altérer le dessin.','Il agit sur l’image composée en dessous. Type, intensité, position, taille, rotation et opacité sont réglables. Gomme, écrêtage, annulation/rétablissement, sauvegarde et PNG/PDF sont pris en charge.','fx active ou désactive l’effet. Dépendant du dessin inférieur, il ne peut être pixellisé seul ou fusionné vers le bas. Utilisez l’export d’image normal.','Partagez les stylos ajoutés avec Préréglages personnels uniquement. Réattribuez leurs raccourcis après importation.']},
    es:{title:'v1.0.2: Compartir registros y nuevos controles',online:'Manual web de vídeo, imagen, grabación, cómics e IA de Multina. Requiere conexión a Internet.',
      share:['En Exportar, arriba, elige Proyecto / obra o Solo registros personalizados. Todos los registros del editor actual se guardan en un .multinacustom.','Vídeo incluye medios, ajustes y fuentes añadidas; imagen, materiales, capas guardadas, estilos y fuentes necesarias; cómic, ajustes y puntas de pinceles añadidos. No incluye proyectos ni sus medios simplemente importados.','Importar identifica automáticamente el editor por el contenido. Añade sin sustituir registros ni modificar proyectos; los nombres repetidos reciben un número. Reasigna los atajos de pinceles importados.','Comparte solo recursos y fuentes que puedas redistribuir. Guarda fuera de las carpetas administradas. Límites: 10000 registros y 64GiB por transferencia; 128 pinceles añadidos en total.','El botón del manual y 1_Multina_Manual.html abren este manual web en el idioma de la aplicación o del navegador. Requiere Internet.'],
      video:['Texto, Mosaico y Desenfoque del menú contextual de capas se crean en el cabezal, no en el puntero.','R, por defecto, prioriza el hueco delimitado bajo el puntero aunque haya un clip seleccionado. Nada cambia hasta elegir esta pista o todas. Excluye pistas bloqueadas, clips y el vacío tras el último clip.','Al arrastrar hacia los bordes, el cabezal permanece visible mientras se desplaza hasta los límites reales, incluso por zonas vacías.','El porcentaje entero es una estimación basada en trabajo real, con actualizaciones aproximadamente cada diez segundos de actividad. El tiempo solo no lo aumenta; 100% significa terminado. Puede haber saltos.'],
      importVideo:'Para importar vídeo editable, selecciona project.json dentro de .veproject. Conserva toda la carpeta junto con sus recursos.',
      image:['Cambiar Mosaico/Desenfoque actualiza la etiqueta y el nombre automático de la capa. Los nombres personalizados se conservan.','Comparte materiales, capas guardadas, estilos y fuentes añadidas mediante Solo registros personalizados.'],
      comic:['Mosaico/Desenfoque está después de Elipse. Elige una capa visible editable y arrastra en el lienzo. El efecto se añade encima sin alterar el dibujo original.','Afecta a la composición inferior. Ajusta tipo, intensidad, posición, tamaño, rotación y opacidad. Admite borrador, recorte, deshacer/rehacer, guardado y PNG/PDF.','fx activa o desactiva el efecto. No se puede rasterizar solo ni combinar hacia abajo porque depende del dibujo inferior. Usa la exportación de imagen normal.','Para todos los pinceles añadidos, exporta Solo registros personalizados y reasigna sus atajos al importarlos.']},
    'pt-BR':{title:'v1.0.2: Compartilhar registros e novos controles',online:'Manual online de vídeo, imagem, gravação, quadrinhos e IA do Multina. Requer Internet.',
      share:['Em Exportar, no topo, escolha Projeto / obra ou Somente registros personalizados. Todos os registros do editor atual são salvos em .multinacustom.','Vídeo inclui mídias, ajustes e fontes adicionadas; imagem inclui materiais, camadas salvas, estilos e fontes necessárias; quadrinhos inclui ajustes e pontas de canetas adicionadas. Projetos e suas mídias apenas importadas ficam de fora.','Importar detecta o editor pelo conteúdo. Adiciona sem substituir registros ou mudar projetos; nomes repetidos recebem um número. Reatribua os atalhos das canetas importadas.','Compartilhe apenas materiais e fontes que você pode redistribuir. Salve fora das pastas gerenciadas. Limites: 10000 registros e 64GiB por transferência; 128 canetas adicionadas no total.','O botão do manual e 1_Multina_Manual.html abrem este manual online no idioma do aplicativo ou navegador. Requer conexão com a Internet.'],
      video:['Texto, Mosaico e Desfoque do menu de camadas são criados no indicador de reprodução, não na posição do mouse.','R padrão prioriza o espaço delimitado sob o cursor, mesmo com um clipe selecionado. Nada muda antes de escolher esta faixa ou todas. Não inclui faixas bloqueadas, clipes ou o vazio após o último clipe.','Ao arrastar para as bordas, o indicador permanece visível durante a rolagem até os limites reais, inclusive em áreas vazias.','O percentual inteiro é estimado pelo trabalho real, com atualizações a cada cerca de dez segundos de atividade. O tempo sozinho não o aumenta; 100% indica conclusão. Saltos ainda são possíveis.'],
      importVideo:'Para importar vídeo editável, escolha project.json dentro da pasta .veproject. Mantenha toda a pasta e seus recursos juntos.',
      image:['Mudar Mosaico/Desfoque atualiza o rótulo e o nome automático da camada, preservando nomes personalizados.','Compartilhe materiais, camadas salvas, estilos e fontes adicionadas com Somente registros personalizados.'],
      comic:['Mosaico/Desfoque fica depois de Elipse. Escolha uma camada visível editável e arraste na tela. O efeito é criado acima sem alterar a arte original.','Aplica-se à composição inferior. Ajuste tipo, intensidade, posição, tamanho, rotação e opacidade. Suporta borracha, recorte, desfazer/refazer, salvar e PNG/PDF.','fx liga ou desliga o efeito. Não pode ser rasterizado sozinho nem mesclado abaixo porque depende da arte inferior. Use a exportação normal de imagem.','Exporte todas as canetas adicionadas com Somente registros personalizados e reatribua seus atalhos após importar.']},
    id:{title:'v1.0.2: Berbagi registrasi dan kontrol baru',online:'Manual online Multina untuk video, gambar, rekaman, komik dan AI. Memerlukan koneksi internet.',
      share:['Dari Ekspor di bagian atas, pilih Proyek / karya atau Hanya registrasi kustom. Semua registrasi editor aktif disimpan dalam satu .multinacustom.','Video menyertakan media, pengaturan dan font tambahan; gambar menyertakan materi, lapisan tersimpan, gaya teks dan font yang diperlukan; komik menyertakan pengaturan serta ujung pena tambahan. Proyek dan media yang hanya diimpor ke proyek tidak disertakan.','Impor mendeteksi editor dari isi berkas. Registrasi lama dan proyek tidak diubah; nama yang sama mendapat nomor. Atur ulang pintasan pena komik yang diimpor.','Bagikan hanya materi dan font yang boleh Anda distribusikan. Simpan di luar folder terkelola. Batas: 10000 registrasi dan 64GiB per transfer; total 128 pena tambahan termasuk yang sudah ada.','Tombol manual dan 1_Multina_Manual.html membuka manual online ini dalam bahasa aplikasi atau browser. Memerlukan internet.'],
      video:['Teks, Mosaik dan Blur dari menu lapisan dibuat di posisi playhead, bukan posisi mouse.','R bawaan mengutamakan celah terbatas di bawah kursor meski klip lain dipilih. Tidak ada perubahan sebelum memilih satu/semua trek. Trek terkunci, klip dan ruang setelah klip terakhir tidak termasuk.','Saat diseret ke kedua tepi, playhead tetap terlihat selama gulir sampai batas timeline sebenarnya, termasuk ruang kosong.','Persentase bulat adalah perkiraan berdasarkan kemajuan nyata, diperbarui sekitar setiap sepuluh detik saat ada kemajuan. Waktu saja tidak menaikkannya; 100% berarti selesai. Lompatan angka masih mungkin.'],
      importVideo:'Untuk mengimpor proyek video, pilih project.json di dalam folder .veproject. Simpan seluruh folder dan sumber dayanya bersama.',
      image:['Mengubah Mosaik/Blur memperbarui label dan nama lapisan otomatis. Nama buatan Anda tetap dipertahankan.','Bagikan materi, lapisan tersimpan, gaya teks dan font tambahan melalui Hanya registrasi kustom.'],
      comic:['Mosaik/Blur ada setelah Elips. Pilih lapisan terlihat yang dapat diedit lalu seret di kanvas. Efek ditambahkan di atasnya tanpa mengubah gambar asli.','Efek diterapkan pada komposit di bawah. Atur jenis, kekuatan, posisi, ukuran, rotasi dan opasitas. Mendukung penghapus, clipping, undo/redo, simpan serta PNG/PDF.','fx mengaktifkan/nonaktifkan efek. Karena merujuk gambar di bawah, efek tidak dapat diraster sendiri atau digabung ke bawah. Gunakan ekspor gambar biasa.','Ekspor semua pena tambahan melalui Hanya registrasi kustom. Atur ulang pintasannya setelah impor.']},
    'zh-Hans':{title:'v1.0.2：分享自定义注册项与新操作',online:'Multina视频、图片、录屏、漫画及AI联动在线说明书。需要互联网连接。',
      share:['顶部“导出”可选择“项目／作品”或“仅自定义注册项”。后者将当前编辑器的全部注册项保存为一个.multinacustom文件。','视频包含注册素材、设置及额外字体；图片包含自定义素材、保存图层、文字样式及所需字体；漫画包含额外笔刷的设置和笔尖。不包含作品及仅导入作品的素材。','顶部“导入”根据文件内容自动识别编辑器。只追加，不覆盖已有注册项，不更改作品；重名添加编号。漫画笔刷导入后需重新设置快捷键。','请只分享有权再分发的素材和字体，保存到管理文件夹之外。每次最多10000项及64GiB素材；额外漫画笔刷总计最多128项，含已有笔刷。','说明书按钮及1_Multina_Manual.html会打开此在线说明书，分别使用应用或浏览器语言。需要互联网连接。'],
      video:['图层右键菜单中的文字、马赛克及模糊创建在播放头位置，而非鼠标位置。','默认R键优先选择鼠标下有界限的空隙，即使另一个片段已被选中。选择本轨／全部轨之前不会移动素材。锁定轨道、片段上方及最后片段之后的空白不适用。','向左右边缘拖动播放头时，滚动会保持播放头可见，并可到达时间轴实际边界，包括无素材区域。','导出采用基于实际进展的整数估计，处理持续推进时约每十秒更新。不会仅按时间增加；完成前不会到100%。数值仍可能跳变。'],
      importVideo:'导入视频工程时，请选择.veproject文件夹中的project.json。请完整保留文件夹及素材结构。',
      image:['切换马赛克／模糊时，设置标题和自动图层名会联动；保留自定义名称。','选择“仅自定义注册项”可分享素材、保存图层、文字样式和额外字体。'],
      comic:['椭圆右侧新增马赛克／模糊。选择可编辑且可见的图层，再在画布上拖动；效果添加在该图层上方，不修改原画。','作用于下方合成画面；可调整类型、强度、位置、尺寸、旋转和不透明度。支持橡皮、剪贴、撤销／重做、保存及PNG/PDF导出。','fx可开关效果。因其依赖下方原画，不能单独栅格化或向下合并；完成画面请使用普通图片导出。','选择“仅自定义注册项”可批量分享额外笔刷；导入后重新设置快捷键。']},
    'zh-Hant':{title:'v1.0.2：分享自訂登錄項目與新操作',online:'Multina影片、圖片、螢幕錄影、漫畫及AI連動線上說明書。需要網際網路連線。',
      share:['頂部「匯出」可選「專案／作品」或「僅自訂登錄項目」。後者將目前編輯器的全部登錄項目存成一個.multinacustom檔案。','影片包含登錄素材、設定及額外字型；圖片包含自訂素材、儲存圖層、文字樣式及所需字型；漫畫包含額外筆刷的設定和筆尖。不包含作品及僅匯入作品的素材。','頂部「匯入」依檔案內容自動識別編輯器。只新增，不覆蓋現有登錄項目或更改作品；同名加上編號。漫畫筆刷匯入後需重設快速鍵。','請僅分享有權再散布的素材與字型，存到管理資料夾以外。每次最多10000項及64GiB素材；額外漫畫筆刷總計最多128項，含現有筆刷。','說明書按鈕與1_Multina_Manual.html會開啟此線上說明書，分別使用應用程式或瀏覽器語言。需要網際網路連線。'],
      video:['圖層右鍵選單中的文字、馬賽克及模糊建立在播放頭位置，而非滑鼠位置。','預設R鍵優先選擇滑鼠下有界限的空隙，即使已選取其他片段。選擇本軌／全部軌之前不移動素材。鎖定軌道、片段上方及最後片段後方空白不適用。','向左右邊缘拖曳播放頭時，捲動保持播放頭可見，並可到達時間軸實際邊界，包括無素材區域。','匯出採用基於實際進展的整數估計，處理持續推進時約每十秒更新。不會僅按時間增加；完成前不會到100%。數值仍可能跳動。'],
      importVideo:'匯入影片專案時，請選擇.veproject資料夾中的project.json。請完整保留資料夾及素材結構。',
      image:['切換馬賽克／模糊時，設定標題與自動圖層名稱連動；保留自訂名稱。','選擇「僅自訂登錄項目」可分享素材、儲存圖層、文字樣式及額外字型。'],
      comic:['橢圓右側新增馬賽克／模糊。選可編輯且可見的圖層，再於畫布拖曳；效果加在該圖層上方，不修改原畫。','套用至下方合成畫面，可調類型、強度、位置、尺寸、旋轉及不透明度。支援橡皮擦、剪裁、復原／重做、儲存及PNG/PDF匯出。','fx可切換效果。因依賴下方原畫，不能單獨點陣化或向下合併；完成畫面請用普通圖片匯出。','選擇「僅自訂登錄項目」可批次分享額外筆刷；匯入後重設快速鍵。']},
    ko:{title:'v1.0.2: 사용자 등록 공유와 새로운 조작',online:'Multina 영상·이미지·녹화·만화·AI 연동 웹 설명서. 인터넷 연결이 필요합니다.',
      share:['위쪽 내보내기에서 프로젝트 / 작품 또는 사용자 등록만을 선택합니다. 현재 편집기의 모든 등록을 하나의 .multinacustom 파일로 저장합니다.','영상은 등록 소재·설정·추가 글꼴, 이미지는 소재·저장 레이어·문자 스타일·필요한 글꼴, 만화는 추가 펜 설정·펜촉을 포함합니다. 작품과 작품에만 가져온 소재는 제외됩니다.','가져오기는 파일 내용으로 편집기를 자동 인식합니다. 기존 등록을 덮어쓰거나 작품을 변경하지 않고 추가하며, 같은 이름에는 번호를 붙입니다. 만화 펜 단축키는 다시 설정하세요.','재배포 가능한 소재와 글꼴만 공유하고 관리 폴더 밖에 저장하세요. 한 번에 10000개·64GiB까지, 추가 만화 펜은 기존 포함 128개까지입니다.','설명서 버튼과 1_Multina_Manual.html은 이 웹 설명서를 앱 또는 브라우저 언어로 엽니다. 인터넷 연결이 필요합니다.'],
      video:['레이어 우클릭의 텍스트·모자이크·블러는 마우스가 아닌 재생 헤드 위치에 생성됩니다.','기본 R은 다른 클립이 선택되어도 커서 아래의 유한한 빈 구간을 우선합니다. 이 트랙/모든 트랙을 선택하기 전에는 이동하지 않습니다. 잠긴 트랙, 클립 위, 마지막 클립 뒤 빈 공간은 제외됩니다.','양쪽 가장자리로 헤드를 드래그하면 헤드가 보이는 위치에서 스크롤하며, 소재 없는 구간을 포함한 실제 타임라인 끝까지 이동합니다.','진행률은 실제 처리에 기반한 정수 추정치이며 작업이 진행 중이면 약 10초마다 갱신합니다. 시간만으로 증가하지 않으며 완료 전 100%가 되지 않습니다. 수치가 크게 바뀔 수도 있습니다.'],
      importVideo:'영상 프로젝트를 가져올 때 .veproject 폴더 안의 project.json을 선택하세요. 전체 폴더와 소재 구조를 함께 보관하세요.',
      image:['모자이크/블러 전환 시 설정 표시와 자동 레이어 이름이 연동됩니다. 직접 정한 이름은 유지합니다.','사용자 등록만으로 소재·저장 레이어·문자 스타일·추가 글꼴을 공유할 수 있습니다.'],
      comic:['타원 오른쪽의 모자이크/블러를 선택하고 편집 가능한 표시 레이어에서 캔버스를 드래그합니다. 원본을 바꾸지 않고 그 위에 영역 효과를 추가합니다.','아래 합성 화면에 적용합니다. 종류·강도·위치·크기·회전·불투명도를 조절합니다. 지우개·클리핑·실행 취소/다시 실행·저장·PNG/PDF를 지원합니다.','fx로 효과를 켜고 끕니다. 아래 그림에 의존하므로 단독 래스터화나 아래 병합은 불가합니다. 완성 이미지는 일반 이미지 내보내기를 사용하세요.','추가 펜 전체를 사용자 등록만으로 공유하고 가져온 후 단축키를 다시 설정하세요.']},
    th:{title:'v1.0.2: แชร์รายการและการควบคุมใหม่',online:'คู่มือออนไลน์ของ Multina สำหรับวิดีโอ ภาพ การบันทึก การ์ตูนและ AI ต้องเชื่อมต่ออินเทอร์เน็ต',
      share:['จากส่งออกด้านบน เลือกโปรเจกต์ / ผลงาน หรือรายการที่ลงทะเบียนเองเท่านั้น รายการทั้งหมดของเครื่องมือปัจจุบันจะรวมในไฟล์ .multinacustom','วิดีโอรวมสื่อ การตั้งค่าและฟอนต์เพิ่ม ภาพรวมวัสดุ เลเยอร์ที่บันทึก รูปแบบข้อความและฟอนต์ที่จำเป็น การ์ตูนรวมการตั้งค่าและหัวปากกาที่เพิ่ม ไม่รวมโปรเจกต์หรือสื่อที่นำเข้าเฉพาะโปรเจกต์','นำเข้าตรวจหาประเภทจากเนื้อหาไฟล์ เพิ่มโดยไม่แทนที่รายการหรือเปลี่ยนผลงาน ชื่อซ้ำจะมีเลขต่อท้าย ตั้งปุ่มลัดของปากกาที่นำเข้าใหม่','แชร์เฉพาะวัสดุและฟอนต์ที่มีสิทธิ์แจกจ่าย บันทึกนอกโฟลเดอร์จัดการ จำกัด 10000 รายการและสื่อ 64GiB ต่อครั้ง ปากกาการ์ตูนเพิ่มเติมรวมของเดิมสูงสุด 128 รายการ','ปุ่มคู่มือและ 1_Multina_Manual.html เปิดคู่มือออนไลน์นี้ตามภาษาของแอปหรือเบราว์เซอร์ ต้องใช้อินเทอร์เน็ต'],
      video:['ข้อความ โมเสกและเบลอจากเมนูเลเยอร์สร้างที่ตำแหน่งหัวเล่น ไม่ใช่ตำแหน่งเมาส์','R เริ่มต้นให้ช่องว่างที่มีขอบเขตใต้เคอร์เซอร์สำคัญกว่าคลิปที่เลือก ไม่มีการย้ายก่อนเลือกแทร็กนี้หรือทุกแทร็ก ไม่รวมแทร็กล็อก บนคลิปหรือพื้นที่หลังคลิปสุดท้าย','ลากหัวเล่นไปที่ขอบทั้งสองเพื่อเลื่อนโดยรักษาหัวเล่นให้มองเห็น จนถึงขอบจริงของไทม์ไลน์รวมพื้นที่ว่าง','เปอร์เซ็นต์จำนวนเต็มเป็นค่าประมาณจากงานที่คืบหน้าจริง อัปเดตประมาณทุกสิบวินาทีระหว่างมีความคืบหน้า เวลาอย่างเดียวไม่ทำให้เพิ่มและ 100% ใช้เมื่อเสร็จแล้ว ตัวเลขยังอาจกระโดดได้'],
      importVideo:'เมื่อนำเข้าโปรเจกต์วิดีโอ เลือก project.json ในโฟลเดอร์ .veproject เก็บทั้งโฟลเดอร์และโครงสร้างสื่อไว้ด้วยกัน',
      image:['สลับโมเสก/เบลอจะเปลี่ยนป้ายการตั้งค่าและชื่อเลเยอร์อัตโนมัติ โดยคงชื่อที่ตั้งเองไว้','แชร์วัสดุ เลเยอร์ที่บันทึก รูปแบบข้อความและฟอนต์เพิ่มด้วยรายการที่ลงทะเบียนเองเท่านั้น'],
      comic:['โมเสก/เบลออยู่ถัดจากวงรี เลือกเลเยอร์ที่แสดงและแก้ไขได้แล้วลากบนผืนผ้าใบ เพิ่มเอฟเฟกต์ด้านบนโดยไม่เปลี่ยนภาพเดิม','ใช้กับภาพประกอบรวมด้านล่าง ปรับประเภท ความแรง ตำแหน่ง ขนาด มุมและความทึบ รองรับยางลบ คลิป ย้อนกลับ/ทำซ้ำ บันทึกและ PNG/PDF','fx เปิด/ปิดเอฟเฟกต์ เนื่องจากอ้างอิงภาพด้านล่างจึงไม่รองรับแปลงเป็นราสเตอร์แยกหรือรวมลง ใช้ส่งออกภาพปกติสำหรับภาพสำเร็จ','แชร์ปากกาที่เพิ่มทั้งหมดด้วยรายการที่ลงทะเบียนเองเท่านั้น และตั้งปุ่มลัดใหม่หลังนำเข้า']}
  };
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  for(const [lang,locale]of Object.entries(bundle.locales)){
    const t=copy[lang];if(!t)throw Error('Missing v1.0.2 manual language '+lang);
    locale.data.meta.version='1.0.2';locale.data.meta.build=117;locale.data.chrome.description=t.online;
    for(const page of Object.values(locale.pages)){page.body=page.body.replaceAll('1.0.1','1.0.2').replace(/\bbuild\s+116\b/gi,'build 117');page.description=t.online;}
    for(const id of ['index','video','image','comic']){
      const definition=locale.data.pages.find(p=>p.id===id),page=locale.pages[id];
      const area=id==='index'?'common':'top',group=id==='index'?'output':id==='comic'?'effects':'support',section='v102-update';
      if(!definition||!page||!page.body.includes('<article id="explanations"'))throw Error('Missing manual section '+id);
      definition.sections.unshift({id:section,title:t.title,group,area,promoted:false});
      const paragraphs=id==='index'?t.share:id==='video'?[...t.video,t.importVideo]:t[id];
      const html='<details class="guide-item left" id="'+section+'" data-group="'+group+'" data-area="'+area+'" data-order="-2" open><summary class="guide-heading"><img class="guide-face" data-embedded-asset="assets/art/face-smile-left.png" alt="" loading="lazy"><span class="heading-bubble"><span class="heading-meta"><span>'+esc(definition.areas[area])+'</span><span>v1.0.2</span></span><span class="heading-title">'+esc(t.title)+'</span><span class="fold-prompt"><b class="fold-symbol" aria-hidden="true"></b><span class="open-word">'+esc(locale.data.chrome.open)+'</span><span class="close-word">'+esc(locale.data.chrome.close)+'</span></span></span></summary><div class="guide-content">'+paragraphs.map(p=>'<p>'+esc(p)+'</p>').join('')+'<a class="section-link" href="#/'+id+'/'+section+'">'+esc(locale.data.chrome.sectionLink)+'</a></div></details>';
      page.body=page.body.replace(/(<article id="explanations"[^>]*>)/,'$1'+html);
      if(id==='video'){
        // Replace the obsolete folder-picker step, not the .veproject format.
        const marker=page.body.indexOf('id="project-export"'),end=page.body.indexOf('<a class="section-link"',marker);
        if(marker>=0&&end>marker){let part=page.body.slice(marker,end),count=0;part=part.replace(/<li>[\s\S]*?<\/li>/g,item=>++count===3?'<li>'+esc(t.importVideo)+'</li>':item);page.body=page.body.slice(0,marker)+part+page.body.slice(end);}
      }
    }
  }
};
